apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: brain-checkpoint-pvc
  labels:
    app: brain-fdqc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: brain-data-pvc
  labels:
    app: brain-fdqc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: standard
