# Logging Configuration
level: info  # trace, debug, info, warn, error, critical

# Log pattern
pattern: "%Y-%m-%d %H:%M:%S.%e [%l] [%n] %v"

# Output targets
sinks:
  - type: console
    level: info
    colored: true
  
  - type: file
    level: debug
    path: /var/log/brain/brain.log
    rotation:
      max_size: 10485760  # 10MB
      max_files: 5
  
  - type: file
    level: error
    path: /var/log/brain/brain_error.log
    rotation:
      max_size: 10485760
      max_files: 3

# Component-specific log levels
loggers:
  brain.qw: debug
  brain.gw: info
  brain.memory: info
  brain.wiring: debug
  brain.audit: info
